spring:
  application:
    name: dallyrun-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/dallyrun
    username: ${DB_USERNAME:dallyrun}
    password: ${DB_PASSWORD:dallyrun}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
